### PR TITLE
Added travis file

### PR DESCRIPTION
**Pull request by jroper**

### CODE REVIEW

**Comment by benmccann** [comment]
Thanks for setting this up James!

What version of MongoDB does "services:  - mongodb" provide? The tests currently do not pass 2.6, which is something I need your help with. See https://github.com/devbliss/mongojack/issues/71

Also, I'm not sure you even need to specify that at all. The tests now use an embedded mongodb, so it should be downloaded and unzipped when the tests run and shouldn't require mongodb to be installed on the machine already. This makes it much easier to test mongojack against different version of mongodb.

**Comment by bickralf** [comment]
retest this please

**Comment by benmccann** [comment]
I'm still curious if you need the `services:` section or if you can just delete that since we use the embedded mongodb that the tests automatically download and start

**Comment by jroper** [comment]
Hmm... I didn't realise that. We should try deleting it then.

**Comment by benmccann** [comment]
I sent a PR to try deleting it here: https://github.com/mongojack/mongojack/pull/128

Should Travis be leaving a comment on the issue with its status? I don't see anything so wondering if there's some setup left to do...

**Comment by jroper** [comment]
Yeah, there's something weird going on - travis is building it, but it's not updating the commit status. Not sure what's going on, maybe you could raise an issue with travis support?

**Comment by benmccann** [comment]
I don't really have time to at the moment unfortunately

**Comment by jroper** [comment]
Yeah, me either :)

**Pull request merged**
