### PR TITLE
Modify serializers to be safe to use with JsonUnwrapped

### LINKED ISSUE #111: StackOverflowError deserialization objects under certain conditions
Hi I'm getting a StackOverflowError in the following conditions:
1.- The object is created using @JsonCreator
2.- The object has a date property which is not in the document
3.- The document has a date property which is not in the object
Below there is a main class that reproduce this bug.

This error happens with mongojack >= 2.2.0 (actually happens when jackson >= 2.4.0) and can be related with https://github.com/mongojack/mongojack/issues/26 but I'm not sure.

I know that these conditions seems weird but when the structure of the documents change over time this things can occur easily.

The exception stacktrace is:
```
Exception in thread "main" java.lang.StackOverflowError
	at com.fasterxml.jackson.databind.SerializerProvider.<init>(SerializerProvider.java:207)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.<init>(DefaultSerializerProvider.java:60)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.<init>(DefaultSerializerProvider.java:512)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.createInstance(DefaultSerializerProvider.java:526)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.createInstance(DefaultSerializerProvider.java:505)
	at com.fasterxml.jackson.databind.ObjectMapper._serializerProvider(ObjectMapper.java:2846)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1902)
	at com.fasterxml.jackson.databind.util.TokenBuffer.writeObject(TokenBuffer.java:813)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1902)
	at com.fasterxml.jackson.databind.util.TokenBuffer.writeObject(TokenBuffer.java:813)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:37)
	at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1902)
	....
```

Main class that reproduce the issue:
```java
import java.util.Date;

import org.mongojack.DBQuery;
import org.mongojack.DBUpdate;
import org.mongojack.Id;
import org.mongojack.JacksonDBCollection;
import org.mongojack.ObjectId;
import org.mongojack.internal.MongoJackModule;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mongodb.DB;
import com.mongodb.MongoClient;
import com.mongodb.WriteConcern;

public class Main {
   public static void main(String[] args) throws Exception {
      MongoClient client = new MongoClient("localhost");

      DB db = client.getDB("test");
      db.setWriteConcern(WriteConcern.ACKNOWLEDGED);

      ObjectMapper mapper = MongoJackModule.configure(new ObjectMapper());
      mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

      JacksonDBCollection<Pojo, String> pojos = JacksonDBCollection.wrap(db.getCollection("pojos"),
            Pojo.class, String.class, mapper);

      pojos.drop();
      pojos.insert(new Pojo(null, "p1", null));
      pojos.update(DBQuery.is("name", "p1"), DBUpdate.set("invalidDate", new Date()));

      Pojo pojo = pojos.findOne(DBQuery.is("name", "p1"));
      System.out.println(pojo);
   }

   // @JsonIgnoreProperties("invalidDate") // works
   // @JsonIgnoreProperties(ignoreUnknown = true) // doesn't work
   public static class Pojo {
      @Id
      @ObjectId
      private String id;

      private String name;

      private Date date;

      @JsonCreator
      public Pojo(@Id @ObjectId String id, @JsonProperty("name") String name, @JsonProperty("date") Date date) {
         super();
         this.id = id;
         this.name = name;
         this.date = date;
      }

      public String getId() {
         return id;
      }

      public String getName() {
         return name;
      }

      public Date getDate() {
         return date;
      }

      @Override
      public String toString() {
         return name;
      }
   }
}
```

### PR DESCRIPTION
**Pull request by kdkeck**
May resolve #111, #26.

### CODE REVIEW

**Comment by ractive** [comment]
We face this exact issue, while migrating from mongojack 2.1 to 2.6.
Is there any reason why this fix has not been merged yet?

**Comment by kdkeck** [comment]
I think it was just forgotten about--the maintainers have been rather busy lately.  I've merged it in now, and will try to get a new minor release out shortly.

**Comment by ractive** [comment]
Thanks for this quick response! We're looking forward to the new release!

**Comment by ractive** [comment]
> [...] and will try to get a new minor release out shortly.

Are there any plans to release a version 2.6.1 in the near future?

**Comment by kdkeck** [comment]
@benmccann is cutting one now.

**Pull request merged**
