### PR TITLE
Use custom ObjectMapper in JacksonCodecRegistry when building JacksonMongoCollection

### PR DESCRIPTION
**Pull request by sventorben**
The JacksonCodecRegistry should use the provided ObjectMapper and view when it is initialized.

### CODE REVIEW

**Comment by benmccann** [comment]
Is there a test you can add that would have failed with the old behavior and passes now?

**Comment by sventorben** [comment]
I have copied the test for custom object mapper used with JacksonDBCollection and adjusted it to work with the JacksonMongoCollection.

**Comment by benmccann** [comment]
I don't see that the test you added uses a view or tests the constructor you modified. Maybe I'm just missing it, but I'm not sure how it would test the new code

Also, the tests should go in a file named TestJacksonMongoCollection for consistency

**Comment by sventorben** [comment]
The constructor is private and therefore the test uses it implicitly by calling the build method of the builder. Look at line 49 https://github.com/mongojack/mongojack/pull/177/files#diff-82661e693913d3a7ba066ed67f80ef0fR49 in the test code. 

Indeed, the test does not use a view, but it uses a custom object mapper. The view is passed through to the JacksonCodecRegistry because the constructor of JacksonCodecRegistry which takes an object mapper requires a view, too.

Regarding consistency when naming tests, there was another test class (TestCustomObjectMapper) for testing the usage of custom object mapper with JacksonDbCollection. Do you still want me to incorporate the tests in TestJacksonMongoCollection or should I rename the test class to something different?

**Comment by benmccann** [comment]
Thanks for the explanation

**Pull request merged**
